version: "3.8"

services:
  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:8000"
    volumes:
      - ./api:/var/www/html
    depends_on:
      - db

  front:
    build:
      context: ./portfolio
      dockerfile: Dockerfile
    container_name: react-front
    ports:
      - "3000:3000"
    volumes:
      - ./portfolio:/app
    stdin_open: true
    tty: true

  db:
    image: mysql:8
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: api
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
